let animal = "Dumbo Octopus";
console.log(animal);
console.log(animal[0]);
console.log(animal[99]);
let phone = "(321)234-3456";
console.log(phone[0]);
console.log(animal);
console.log(animal.length);
console.log(animal[12]);
console.log("lol".length);
console.log("lol"[0]);
console.log(1 + 2);
console.log("lol" + "lol");
let firstName = "River";
let lastName = "Phoenix";
console.log(firstName);
console.log(lastName);
console.log(firstName + lastName);
let fullName = firstName + " " + lastName;
console.log(fullName);
let result = 1 + "hi";
console.log(result);
console.log(typeof result);
console.log(typeof 1);
console.log("1" + "hi");
