console.log("asdfghjkl".toUpperCase());
let msg = "haha that is so funny!";
console.log(msg);
console.log(msg.indexOf("h"));
console.log(msg.indexOf("!"));
console.log(msg.indexOf("$"));
console.log(msg.indexOf("is"));
console.log(msg.slice(5));
console.log(msg.slice(5, 9));
console.log(msg.slice(5, 10));
console.log(msg.slice(10, 12));
console.log(msg.slice(-6));
console.log(msg.replace("haha", "lolololol"));
console.log(msg.replace("h", "H"));
console.log("lol".repeat(10));
