const nums = [23, 45, 99];
console.log(nums);
console.log(nums[1]);
const person = { firstName: "Mick", lastName: "Jagger" };
console.log(person);
console.log(person["lastName"]);
console.log(person.firstName);
console.log(person.lastName);
console.log("wdfw".length);
const years = { 1999: "GOOD", 2020: "BAD" };
console.log(years);
console.log(years["1999"]);
console.log(years["2020"]);
console.log(years[1999]);
const dumbdumb = { true: "dat", null: "zrdxtfcgvhbijn" };
console.log(dumbdumb);
console.log(dumbdumb["true"]);
console.log(dumbdumb["null"]);
console.log(person["first" + "Name"]);
const birthYear = 1999;
console.log(years[birthYear]);
