console.log(1 > 3);
console.log(1 < 3);
console.log(-1 > 20);
console.log(-1 > -1);
console.log(-1 <= -1);
console.log(-1 <= 10);
let age = 33;
console.log(age >= 18);
console.log(age);
console.log("a");
console.log("A" < "a");
console.log("@" < "A");
