console.log("monday"[0]);
let days = ["Monday", "Tuesday", "Wednesday"];
console.log(days);
console.log(days[0]);
console.log(days.length);
console.log(days[2]);
console.log(days[3]);
console.log(days[30]);
console.log(days[300]);
console.log(days[1]);
console.log(days[1][0]);
let firstName = "colt";
console.log(firstName);
console.log(firstName[0]);
let colors = ["rad", "orange", "yalloww"];
colors[0] = "red";
colors[1] = 70;
colors[2] = "yellow";
console.log(colors);
colors[10] = "indigo";
console.log(colors);
console.log(colors.length);
console.log(colors[5]);
console.log(colors[6]);
console.log(colors[9]);
console.log(colors[10]);
let beatles = ["paul", "john", "george"];
beatles[3] = "ringo";
console.log(beatles);
