let movieLine = ["tom", "nancy"];
movieLine[2] = "pablo";
console.log(movieLine);
movieLine.push("oliver");
console.log(movieLine);
let cat = "blue";
console.log(cat.toUpperCase());
console.log(cat);
movieLine.push("eva");
console.log(movieLine);
movieLine.push("harry", "herminoe");
console.log(movieLine);
movieLine.pop();
console.log(movieLine);
let person = movieLine.pop();
console.log(person);
console.log(movieLine);
let barbell = [];
barbell.push(45);
barbell.push(45);
barbell.push(25);
barbell.push(10);
barbell.push(2.5);
console.log(barbell);
barbell.pop();
