let movieLine = ["tom", "nancy", "pablo", "oliver", "eva"];
console.log(movieLine);
console.log(movieLine.shift());
console.log(movieLine);
let nextPatron = movieLine.shift();
console.log(nextPatron);
console.log(movieLine);
movieLine.push("colt");
movieLine.shift();
movieLine.shift();
movieLine.shift();
movieLine.shift();
console.log(movieLine);
movieLine.push("jerry", "deniz", "kevin", "carly");
console.log(movieLine);
movieLine.unshift("VIP");
console.log(movieLine);
movieLine.shift();
