let colors = ["red", "orange", "yellow", "green", "blue", "indigo", "violet"];
console.log(colors.slice());
let coolColors = colors.slice(3);
console.log(coolColors);
let warmColors = colors.slice(0, 3);
console.log(warmColors);
let days = ["Monday", "Tuesday", "Wednesday"];
colors.splice(5, 1);
console.log(colors);
console.log(days);
days.splice(1, 2);
console.log(days);
colors.splice(1, 0, "red-orange");
console.log(colors);
colors.splice(4, 0, "yellow-green", "forestgreen");
console.log(colors);
colors.splice(2, 2, "DELETED!!");
console.log(colors);
let scores = [1, 70, 100, 2500, 9, -12, 0, 34];
console.log(scores.sort());
